version: '3.7'
services:
  app:
    image: app-image
    container_name: app-name
    ports:
      - 8080:8080
      - 9669:9669
    environment:
      - ENVIRONMENT=prod
    networks:
      - appnetwork

  db:
    image: postgres:11.1
    container_name: prod-db
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
        - ../../postgres-data:/var/lib/postgresql/data
    networks:
      - appnetwork

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy-config:/etc/caddy/
      - ../../caddy-data:/data
    networks:
      - appnetwork

networks:
  appnetwork: